export default {
    UPDATE_USER: 'UPDATE_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    SET_AID_TYPE: 'SET_AID_TYPE',
    SET_CALL_REASON: 'SET_CALL_REASON',
    ADD_EXTRA_DETAILS: 'ADD_EXTRA_DETAILS',
    SET_HEALTH_ASSISTANCE_DETAILS: 'SET_HEALTH_ASSISTANCE_DETAILS',
    ADD_FEEDBACK_SCORE: 'ADD_FEEDBACK_SCORE',
    ADD_FEEDBACK_DETAILS: 'ADD_FEEDBACK_DETAILS',
    CLEAR_FORM_STORE: 'CLEAR_FORM_STORE',
};
